Revert "[maven-release-plugin] prepare release 24.0.0"
This reverts commit 81932b61d6c0378587a929f951ea6c6c9c59cb82.

The deployment has failed central verification:
pkg:maven/io.lighty.applications.rcgnmi/lighty-gnmi-device-simulator@24.0.0
Error: Sources must be provided but not found in entries
Error: Javadocs must be provided but not found in entries
Error: Project name is missing

Since no artifacts were deployed, we can revert, fix packaging and try
again.

JIRA: LIGHTY-434
Signed-off-by: Ivan Hrasko <ivan.hrasko@pantheon.tech>