Add missing SessionHandler
Add session handler to jetty server initialization to remove the exception
which was being thrown when using authentication:
java.lang.IllegalStateException: No SessionManager"

JIRA: LIGHTY-400
Signed-off-by: tobias.pobocik <tobias.pobocik@pantheon.tech>